image: python:3.9

stages:
  - build
  - deploy

build_docs:
  stage: build
  script:
    - pip install poetry
    - poetry install --with docs
    - poetry run sphinx-apidoc -o docs/source two
    - poetry run sphinx-build -b html docs/source docs/_build/html
  artifacts:
    paths:
      - docs/_build/html
  only:
    - master # or any branch you want to deploy docs from

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r docs/_build/html/* public/ # Copy built documentation to public folder
  artifacts:
    paths:
      - public
  only:
    - main # or your default branch
